HM_GB/urls.py
from django.urls import path
from . import views

app_name = 'HM_GB'

urlpatterns = [
    path('<mesname>', views.DetailView, name='detail_mes_data'),
    path('', views.IndexView, name='index'),
    path('signup/', views.signup, name='signup'),
    path('signin/', views.signin, name='signin'),
    path('signout/', views.signout, name='signout'),
    path('change_pw/', views.change_pw, name='change_pw'),
    path('changedNoun/', views.changedNoun, name='changedNoun'),
    #path('<int:question_id>/', views.DetailView.as_view(), name='detail'),
    #path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    #path('<int:question_id>/vote/', views.vote, name='vote'),
]

HMsite/urls.py
from django.contrib import admin
from django.urls import include, path
urlpatterns = [
    path('HM_GB/', include('HM_GB.urls')),
    path('admin/', admin.site.urls),
]

HM_GB/models.py
import datetime
from django.db import models
from django.utils import timezone

class TranslateModel(models.Model):
    SubFile_Name = models.CharField(max_length=25,null=True)
    SubFile_Lineindex = models.IntegerField(null=True)
    Translate_text_JPN = models.TextField(null=True)
    Translate_text_ENG = models.TextField(null=True)
    Translate_text_KOR1 = models.TextField(null=True)
    Translate_text_KOR2 = models.TextField(null=True,blank=True)
    Translate_date = models.CharField(max_length=25)
    Translate_IsTranslated = models.BooleanField(default=False)
    Translate_IsInspected = models.BooleanField(default=False)
    Translate_text_KORLOG = models.TextField(null=True, blank=True)
    Translate_LastEditor = models.TextField(null=True, blank=True)
# Create your models here.

HM_GB/forms.py
from django.forms import ModelForm
from django.contrib.auth.models import User
from django import forms

class SignupForm(ModelForm):  # 회원가입을 제공하는 class이다.
    password_check = forms.CharField(max_length=200, widget=forms.PasswordInput())
    # 아쉽게도 User 모델에서는 password_check 필드를 제공해주지 않는다.
    # 따라서 따로 password_check 필드를 직접 정의해줄 필요가 있다.
    # 입력 양식은 type은 기본이 text이다. 따라서 다르게 지정해주고 싶을 경우 widget을 이용한다.
    # widget=forms.PasswordInput()은 입력 양식을 password로 지정해주겠다는 뜻이다.

    field_order = ['username', 'password', 'password_check', 'first_name', 'email']

    # field_order는 만들어지는 입력양식의 순서를 정해준다.
    # 여기서 사용한 이유는 password 바로 밑에 password_check 입력양식을 추가시키고 싶어서이다.
    # 만약 따로 field_order를 지정해주지않았다면, password_check는 맨 밑에 생성된다.

    class Meta:
        model = User
        exclude = ()
        widgets = {'password': forms.PasswordInput}
        fields = ['username', 'password',  'first_name', 'email']


# User model에 정의된 username, passwordm last_name, first_name, email을 입력양식으로

class SigninForm(ModelForm):  # 로그인을 제공하는 class이다.
    class Meta:
        model = User
        exclude = ()
        widgets = {'password': forms.PasswordInput}
        fields = ['username', 'password']

HM_GB/views.py
"""
    각종 데이터를 받아와 처리하는 파이썬 파일
"""

from django.http import HttpResponse, HttpResponseRedirect, HttpResponseNotFound
from django.shortcuts import render, redirect
from django.views import generic
from django.urls import reverse
from django.template import loader
from django.utils import timezone
from django.contrib.auth.models import User
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.hashers import check_password
from django.db import connection
from .models import TranslateModel
from .forms import SigninForm, SignupForm
from django.forms import ModelForm


def IndexView(request):
    template_name = 'HM_GB/index.html'
    return render(request,template_name)


#실제로 오고가는 파일 처리하는 함수
#DetailView(요청,처리할 파일이름)
def DetailView(request,mesname):
    TEXT_FILE_LIST = ["event_mes_data","mes_data"]  #파일 이름들
    Translate_list = TranslateModel.objects.all()
    context = {'Translate_list': Translate_list,'Request_mes': mesname}
    if(mesname not in TEXT_FILE_LIST):
        return HttpResponseNotFound('<h1>Page not found</h1>') #파일 이름들이 아닌 다른항목으로 접근하면 404
    template_name = 'HM_GB/detail_mes_data.html'
    if request.method == "POST":    #POST 메서드일경우 Query에 저장
        POSTdata = request.POST
        print(POSTdata)
        print("\n\n\n\n\n\n")
        if (POSTdata["PostTranslated"] == "true"):
            IsTranslated = 1
        else:
            IsTranslated = 0
        if (POSTdata["PostInspected"] == "true"):
            IsInspected = 1
        else:
            IsInspected = 0
        with connection.cursor() as cursor:
            update_string = 'UPDATE HM_GB_translatemodel SET Translate_text_KOR2 = "%s", Translate_date = "%s", Translate_IsTranslated = %d, Translate_IsInspected = %d, Translate_text_KORLOG = "%s", Translate_LastEditor = "%s" WHERE id = %d' % (POSTdata["PostTxtKOR2"],
                           POSTdata["PostNowtime"],
                           IsTranslated,
                           IsInspected,
                           POSTdata["PostKORLog"],
                           POSTdata["PostEditor"],
                           int(POSTdata["PostPK"]))
            cursor.execute(update_string)
        return render(request,template_name)
    return render(request,template_name,context)

def changedNoun(request):
    return render(request, 'HM_GB/changedNoun.html')

def signup(request):
    return HttpResponseNotFound('<h1>Page not found</h1>')
    """
    if request.method == "GET":
        return render(request, 'HM_GB/signup.html', {'f': SignupForm()})
    elif request.method == "POST":
        form = SignupForm(request.POST)
        if form.is_valid():
            if form.cleaned_data['password'] == form.cleaned_data['password_check']:
                # cleaned_data는 사용자가 입력한 데이터를 뜻한다.
                # 즉 사용자가 입력한 password와 password_check가 맞는지 확인하기위해 작성해주었다.

                new_user = User.objects.create_user(form.cleaned_data['username'], form.cleaned_data['email'],
                                                    form.cleaned_data['password'])
                # User.object.create_user는 사용자가 입력한 name, email, password를 가지고 아이디를 만든다.
                # 바로 .save를 안해주는 이유는 User.object.create를 먼저 해주어야 비밀번호가 암호화되어 저장된다.
                new_user.first_name = form.cleaned_data['first_name']
                # 나머지 입력하지 못한 last_name과, first_name은 따로 지정해준다.
                new_user.save()

                return render(request, 'HM_GB/index.html')
            else:
                return render(request, 'HM_GB/signup.html', {'f': form,
                                                                   'error': '비밀번호와 비밀번호 확인이 다릅니다.'})  # password와 password_check가 다를 것을 대비하여 error를 지정해준다.
        else:  # form.is_valid()가 아닐 경우, 즉 유효한 값이 들어오지 않았을 경우는
            return render(request, 'HM_GB/signup.html', {'f': form})
    """

# 원래는 error 메시지를 지정해줘야 하지만 따로 지정해주지 않는다.
def signin(request):  # 로그인 기능
    if request.method == "GET":
        print("asd")
        return render(request, 'HM_GB/signin.html', {'f': SigninForm()})
    elif request.method == "POST":
        form = SigninForm(request.POST)
        id = request.POST['username']
        pw = request.POST['password']
        u = authenticate(username=id, password=pw)
        # authenticate를 통해 DB의 username과 password를 클라이언트가 요청한 값과 비교한다.
        # 만약 같으면 해당 객체를 반환하고 아니라면 none을 반환한다.

        if u:  # u에 특정 값이 있다면
            login(request, user=u)  # u 객체로 로그인해라
            return HttpResponseRedirect(reverse('HM_GB:index'))
        else:
            return render(request, 'HM_GB/signin.html', {'f': form, 'error': '아이디나 비밀번호가 일치하지 않습니다.'})





def signout(request):  # logout 기능
    logout(request)  # logout을 수행한다.
    return HttpResponseRedirect(reverse('HM_GB:index'))
    
def change_pw(request):
    context= {}
    if request.method == "POST":
        current_password = request.POST.get("origin_password")
        user = request.user
        if check_password(current_password,user.password):
            new_password = request.POST.get("password1")
            password_confirm = request.POST.get("password2")
            if new_password == password_confirm:
                user.set_password(new_password)
                user.save()
                login(request, user=user)  # u 객체로 로그인해라
                return HttpResponseRedirect(reverse('HM_GB:index'))
            else:
                context.update({'error':"새로운 비밀번호를 다시 확인해주세요."})
        else:
            context.update({'error':"현재 비밀번호가 일치하지 않습니다."})

    return render(request, "HM_GB/change_pw.html",context)

HM_GB/templates/HM_GB/change_pw.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title>Insert title here</title>
	</head>
	<body>
		<div class="container">
			<div class="login_container">
				<div class="error_message">
					{{error}}
				</div>
				<div class="login_title">
					비밀번호는 SHA-256으로 암호화되어있기때문에 저를 포함한 모든 사람이 알지 못합니다.<br>
					Change Password
				</div>
				<form method="POST" action="{% url 'HM_GB:change_pw' %}" class="login_form">
					{% csrf_token %}

					<div class="login_input_container">
						<div class="username_form_text">Origin Password</div>
						<div class="input_container">
							<input class="login_input" name="origin_password" type="password">
						</div>

						<div class="password_form_text"> New Password</div>
						<div class="input_container">
							<input class="login_input" name="password1" type="password">
						</div>
						<div class="confirm_password_form_text">Confirm Password</div>
						<div class="input_container">
							<input class="login_input" name="password2" type="password">
						</div>
					</div>
					<div class="login_btn_container">
						<input type="submit" class="login_btn" value="Submit">
					</div>
			</div>
			</form>
		</div>
	</body>
</html>

HM_GB/templates/HM_GB/changedNoun.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="ko">
<head>
	<title>Translate Form</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body>
  
    <ul>
       <li>스테키 -> 폼나 (공식한글화 명사 적용)</li>
    </ul>

</body>

HM_GB/templates/HM_GB/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="ko">
<head>
	<title>Translate Form</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="{% static 'HM_GB/style.css' %}">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
	<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
	<script src="{% static 'HM_GB/mainjava.js' %}"></script>
	<script src="http://code.jquery.com/jquery-3.4.1.js"></script>
	<script>
	function alertSome()
	{
		alert("번역자 란에 이름을 남기거나\n검수 확인에 관심이 있으신분은\nmirusu400@naver.com로 만들어질 아이디 이름을 이메일 주시면\n아이디 및 임시비밀번호를 발급해 드립니다.");
	}
	</script>
</head>

<body>
{% load static %}
{% if user.is_authenticated %}<!-- 만약 로그인이 되어있는 상태이면 -->
	{{user.first_name}}님 환영합니다.<br> <!-- 다음과같이 출력 -->
	<a href="{% url 'HM_GB:change_pw' %}"><button>비밀번호 변경</button></a>
	<a href="{% url 'HM_GB:signout' %}"><button>로그아웃</button></a> <!-- 로그아웃이 뜨도록 한다. -->
{% else %} <!-- 로그인이 되어있지않다면 -->
	<a href="{% url 'HM_GB:signin' %}"><button>로그인</button></a> <!-- 로그인과-->
	<button onclick="alertSome()">회원가입</button></a>
	<br>
	로그인을 하지 않아도 수정은 가능합니다.
	<!--a href="{% url 'HM_GB:signup' %}"><button>회원가입</button></a> <!-- 회원가입이 뜨도록 한다. -->
{% endif %}
{% block content %}
<!-- 변동부분을 block 지정해준다. -->
{% endblock %}    
    <ul>
       <li><a href="{% url 'HM_GB:detail_mes_data' 'event_mes_data'%}">event_mes_data</a></li>
		<li><a href="{% url 'HM_GB:detail_mes_data' 'mes_data'%}">mes_data</a></li>
		<li><a href="{% url 'HM_GB:changedNoun'%}" target="_blank">바뀐 고유명사 목록</a></li>
    </ul>
	<h2>목장이야기 바람의바자회 번역 및 검수 홈페이지입니다.</h2>
	본 사이트는 크롬에서 가장 잘 작동됩니다.<br> <br>
	위의 각 링크를 누르면 번역 페이지로 이동이 가능합니다. <br>그냥 검수에 참여할 시 글자 크기가 작으므로 150~170%(1920x1080모니터 기준) 으로 확대해서 검수에 참여하시길 바랍니다<br> <br>
	번역을 한 후에 번역완료를 체크하고 저장하시면, 저를 포함한 관리자(회원) 분들이 검수확인을 합니다. <br> <br>
	우측의 버튼에 일어 원본 / 한글 원본을 가져올 수 있고 이를 수정후 Submit 버튼을 누르고 잠시 후 "done"이란 알람이 나오면 정상적으로 저장이 된것입니다. <br>
	Submit버튼을 누르면 자동으로 번역완료가 체크가 됩니다. 또한 비회원의 ip는 수정당시 수정한 본인에게만 제대로 보이며, 새로고침 시 일반적인 별표로만 나옵니다.
	<br> <br>
	검수확인이 된 항목은 일반적으론 수정이 불가능합니다. 만약 이에 대해서 수정을 하고싶다면, mirusu400@naver.com 으로 메일을 주세요. <br> <br>
	<h2>검수 시 지켜야 하는 것들</h2>
	[2B23] 등으로 대괄호가 쳐져있는 부분은 제어코드입니다. 이는 그대로 삽입해주세요. <br>
	[2B23] 와 [2823]은 엔터(\n)을 뜻하는 글자입니다. 각 엔터 사이 들어갈 수 있는 글자는 각종 특수기호(띄어쓰기, 점, 콤마 등)을 포함해 14글자입니다. <br>
	그 외에도, 주인공을 호칭하는 제어코드([2A23])나 글자색을 빨간색([6D20])/파란색([6E20])/일반([6C20])으로 바꾸는 제어코드도 있습니다. 참고해서 번역해주시면 감사하겠습니다. <br>
	<br>
	검수를 참여하다보면 한글 원본 텍스트 뒤에 공백 띄어쓰기(　)가 존재하는데 이는 다 지워주신 상태로 검수 진행해주시면 됩니다.
	<br> <br>
	<h2>QnA</h2>
	<h4>Q. 한 줄의 글자 최대수는 어떻게 되나요?</h4>
	<img src="{% static 'HM_GB/images/char14.png' %}" alt="14char"> </br>
	A. 위에서도 설명했듯이 각종 특수기호(띄어쓰기, 점, 띄어쓰기, 콤마) 등을 포함해 14글자입니다. 이 글자가 넘어가게 되면 강제로 다음 라인으로 넘어가고 다음라인 뒤에 글자가 숨게 됩니다
	<br>
	<br>
	<h4>Q. 글자의 마침표 및 컴마(,)는 일본어 방식으로 해야하나요?</h4>
	A. 일본어 방식으로 해야 합니다만, 일반적인 한국식 점으로 하셔도 상관 없습니다. 추후에 전체 바꾸기를 통해 모두 바꿀 예정입니다.
	
	<br> <br> <br>
	<h2>Changelog</h2>
	<h4> 2019.09.22 </h4>
	<li> Submit 버튼을 누를때 정상적인 텍스트인지 검사하도록 설정하였습니다. </li>
	<li> 번역완료/검수완료를 더 직관적으로 보도록 배경색을 지정했습니다. </li>
	<h4> 2019.09.21 </h4>
	<li> Submit 속도를 대폭 향상시켰습니다. </li>
	<li> 작성한 번역본을 Preview하는 기능을 만들었습니다. </li>
	<li> 파일 항목을 찾을때 번역 라인갯수 / 실제 라인갯수를 추가했습니다.</li>
	<li> 모든 Alert를 Toast 메시지로 바꿨습니다..</li>
</body>

HM_GB/templates/HM_GB/signin.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title>Insert title here</title>
	</head>
	<body>
			{% if error %}
				<p>{{ error }}</p>
			{% endif %}

			<form action="" method="POST">
				{% csrf_token %}
				<table>
					{{ f.as_table }}
				</table>
				<input type="submit" value="로그인">
			</form>
	</body>
</html>

HM_GB/templates/HM_GB/signup.html
<!-- 숨겨진 회원가입 폼입니다. 필요하면 쓰세요. -->

<!DOCTYPE html>

<html>
	<head>
		<meta charset="UTF-8">
		<title>Insert title here</title>
	</head>
	<body>
		{% if error %}
		<h3 style="color:red">{{error}}</h3>
		{% endif %}
		<form action="" method="POST">
			{% csrf_token %}
			<table>
				{{ f.as_table }}
			</table>
			<input type="submit" value="회원가입">

		</form>
	</body>
</html>